server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://192.168.18.129:3306/leyou
    username: root
    password: 123456
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      # rabbitMq相关配置
  rabbitmq:
    host: 1.15.110.209
    username: leyou
    password: leyou
    virtual-host: /leyou
    template: # 定义模板，供AmqpTemplate使用
      exchange: ly.item.exchange   # 指定交换机
      retry: # 配置重试
        initial-interval: 10000ms # 初始化的重试周期
        enabled: true
        max-interval: 30000ms
        multiplier: 2 # 失败后，重试周期时长 * 2
    publisher-confirms: true # 生产者确认，发送失败，需要重试
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5     # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10   # 10秒不发送就过期
 # mybatis 的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    com.leyou.item.mapper: DEBUG